wier/force-app/main/default/objects/Contract_CheckList__c/Contract_CheckList__c.object-meta.xml
<CustomObject>
    <label>PO Checklist</label>
    <nameField>
        <label>Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Handover to Contract Checklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Contract_CheckList__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>Handover_to_Contract_CheckList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Contract_CheckList__c/fields/PO_Attachments__c.field-meta.xml
<CustomField>
    <fullName>PO_Attachments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Attachments</label>
    <referenceTo>PO_Attachments__c</referenceTo>
    <relationshipLabel>Handover to Contract Checklist</relationshipLabel>
    <relationshipName>Handover_to_Contract_CheckList</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIS</fullName>
            </value>
            <value>
                <fullName>Dubai - APS/RE</fullName>
            </value>
            <value>
                <fullName>Dubai - Oilfield</fullName>
            </value>
            <value>
                <fullName>Iraq</fullName>
            </value>
            <value>
                <fullName>NAI</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Saudi</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/CSRDecisionOnBid__c.field-meta.xml
<CustomField>
    <fullName>CSRDecisionOnBid__c</fullName>
    <label>CSR&apos;s Decision on Bid</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Delivery_due_date_as_per_Customer_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_due_date_as_per_Customer_Order__c</fullName>
    <label>Delivery due date as per Customer Order</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Labour_cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_cost__c</fullName>
    <label>Labour cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Material Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/PO_handed_over_to_contract__c.field-meta.xml
<CustomField>
    <fullName>PO_handed_over_to_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO handed over to contract</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/CostSheet__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>CostSheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/CostSheet__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comments (if any)</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>CostSheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Amount__c</fullName>
    <label>Sales Value as per pricing policy (SVP)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Preparation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Preparation_Date__c</fullName>
    <label>Cost Sheet Preparation Date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Discount_amount_if_any__c.field-meta.xml
<CustomField>
    <fullName>Discount_amount_if_any__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Discount/Upselling amount (if any)</description>
    <label>Discount amount (if any)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Labour_Cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cost__c</fullName>
    <label>Labour Cost (L)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Material Cost (M)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Other_Cost__c.field-meta.xml
<CustomField>
    <fullName>Other_Cost__c</fullName>
    <label>Other Costs (O)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/PO_Attachments__c.object-meta.xml
<CustomObject>
    <label>PO Attachments</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>PO Attachments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Assign_Contract_Representative__c.field-meta.xml
<CustomField>
    <fullName>Assign_Contract_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign Contract Representative</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Contracts Manager</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Contracts Representative</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Bedford - Head of Tendering</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Bedford - Tendering Rep</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Barton - Tendering Rep</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>UK CSR+TM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Barton - Head of Tendering</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PO_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/comments_if_any__c.field-meta.xml
<CustomField>
    <fullName>comments_if_any__c</fullName>
    <label>Comments from Tendering</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Customer_document_reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_document_reference__c</fullName>
    <label>Customer document reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Delivery_due_date_as_per_Customer_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_due_date_as_per_Customer_Order__c</fullName>
    <label>Delivery due date as per Customer Order</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Info_clarification_reqd_from_customer__c.field-meta.xml
<CustomField>
    <fullName>Info_clarification_reqd_from_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Info/clarifn. reqd from customer by Tendering</description>
    <label>Clarifn. reqd from customer by Tendering</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>PO Attachments</relationshipLabel>
    <relationshipName>PO_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>Total amount as per Customer Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/PO_handed_over_to_contract__c.field-meta.xml
<CustomField>
    <fullName>PO_handed_over_to_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO handed over to Contract by Tendering</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comment if any</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/CostSheet__c.field-meta.xml
<CustomField>
    <fullName>CostSheet__c</fullName>
    <label>Cost Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.COpportunity__c</field>
            <operation>equals</operation>
            <valueField>CostSheet__c.COpportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostSheet__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Movex_quotation_docs_serial_no__c.field-meta.xml
<CustomField>
    <fullName>Movex_quotation_docs_serial_no__c</fullName>
    <description>Movex Quotation Reference</description>
    <label>Customer Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Submit_for_review__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for review</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/Test_wr_ContractHandoverCheckList.cls
@isTest(SeeAllData = true)
private class  Test_wr_ContractHandoverCheckList {    
    
    static testMethod void UnitTest() {

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        UserRole r = [select Id from userrole where 
        Name = 'Contracts Manager' or 
        Name = 'Contracts Representative'        
        limit 1];
 
        User u = [select Id,Business_Unit__c from user where userroleId =: r.Id limit 1];

        COpportunity__c Opp = new COpportunity__c(Business_Unit__c = 'Oman',CSRDecisionOnBid__c = 'YES');
        insert Opp;
        
        CostSheet__c costSheet = new CostSheet__c(Comment_if_any__c = 'test', discount_amount_if_any__c = 100,COpportunity__c = opp.Id,Labour_Cost__c = 100, Material_Cost__c= 100, Other_Cost__c = 100,Cost_Sheet_Amount__c = 100, Cost_Sheet_Preparation_Date__c = system.today());
        insert costSheet;
        
        Quotation__c Quotation = new Quotation__c(Final__c = true, Submit_for_review__c=true, COpportunity__c = Opp.Id, CostSheet__c  = costSheet.Id, Movex_quotation_docs_serial_no__c = '123');
        insert Quotation;
        
        PO_Attachments__c poa = new PO_Attachments__c(
        Assign_Contract_Representative__c = u.Id,
        Customer_document_reference__c = 'TEST1234567890',
        Opportunity__c = opp.Id,
        PO_Amount__c = 100,
        Info_clarification_reqd_from_customer__c = false,
        PO_handed_over_to_contract__c = false,
        comments_if_any__c = 'testcom',
        Delivery_due_date_as_per_Customer_Order__c = system.today()
        
        );
        insert poa;    


        Contract_CheckList__c conlist = new Contract_CheckList__c(PO_Attachments__c = poa.Id, Opportunity__c = Opp.Id);
        insert conlist;
        
        
        ApexPages.StandardController std = new ApexPages.StandardController(conlist);
        PageReference pageRef = Page.Weir_ContractHandoverCheckList;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', conlist.id);
        wr_ContractHandoverCheckList   cont = new wr_ContractHandoverCheckList (std);
        cont.csave();
        cont.AddRow();
        cont.Cancel();
        

    }
}