wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Quotation_submittal_date__c.field-meta.xml
<CustomField>
    <fullName>Quotation_submittal_date__c</fullName>
    <label>Quotation submittal due date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Bid/No Bid</fullName>
            </value>
            <value>
                <fullName>Approved for Tendering</fullName>
            </value>
            <value>
                <fullName>Quotation under compilation</fullName>
            </value>
            <value>
                <fullName>Tender Under Review</fullName>
            </value>
            <value>
                <fullName>Tender Under Approval</fullName>
            </value>
            <value>
                <fullName>Approved, Make Quotation ready for submitial</fullName>
            </value>
            <value>
                <fullName>Quote Ready for Submital</fullName>
            </value>
            <value>
                <fullName>Quote Submitted to Customer</fullName>
            </value>
            <value>
                <fullName>Customer Contacted for Submitted quote</fullName>
            </value>
            <value>
                <fullName>Quotation under clarification with Customer</fullName>
            </value>
            <value>
                <fullName>PO received</fullName>
            </value>
            <value>
                <fullName>PO Under Clarification</fullName>
            </value>
            <value>
                <fullName>PO handed over to Contract</fullName>
            </value>
            <value>
                <fullName>PO under Review with Contract</fullName>
            </value>
            <value>
                <fullName>PO Approved by Contract</fullName>
            </value>
            <value>
                <fullName>Customer order acknowledged</fullName>
            </value>
            <value>
                <fullName>PO handover to Planning</fullName>
            </value>
            <value>
                <fullName>Job handover to Operations</fullName>
            </value>
            <value>
                <fullName>Job done awaiting contracts sign-off</fullName>
            </value>
            <value>
                <fullName>Job ready for Delivery</fullName>
            </value>
            <value>
                <fullName>job delivered</fullName>
            </value>
            <value>
                <fullName>Opportunity closed</fullName>
            </value>
            <value>
                <fullName>Quote accepted but PO awaited</fullName>
            </value>
            <value>
                <fullName>Customer notified of a Completed Job</fullName>
            </value>
            <value>
                <fullName>Invoicing onhold</fullName>
            </value>
            <value>
                <fullName>Job invoiced in movex</fullName>
            </value>
            <value>
                <fullName>Partial Collected</fullName>
            </value>
            <value>
                <fullName>Fully Collected</fullName>
            </value>
            <value>
                <fullName>Invoice sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Win_Probability__c.field-meta.xml
<CustomField>
    <fullName>Win_Probability__c</fullName>
    <label>Win probability (%)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/CostSheet__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>CostSheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/CostSheet__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>CostSheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Version__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Version__c</fullName>
    <label>Cost Sheet Version</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/CostSheet__c.field-meta.xml
<CustomField>
    <fullName>CostSheet__c</fullName>
    <label>Cost Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.COpportunity__c</field>
            <operation>equals</operation>
            <valueField>CostSheet__c.COpportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostSheet__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Submit_for_review__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for review</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/QuoteEmail_TestClass.cls
@istest
private class QuoteEmail_TestClass{
 static testMethod void myUnitTest() 
 {
   COpportunity__c oppty = new COpportunity__c();
   //oppty.Win_Probability__c = 90;
   oppty.status__c ='Quote Ready for Submital';
   oppty.Quotation_submittal_date__c = System.today();
   insert oppty;
   CostSheet__c costSheet = new CostSheet__c();
   costSheet.Cost_Sheet_Version__c= 'testCostSheet';
   costSheet.COpportunity__c = oppty.ID;
   insert costSheet;
  
   Quotation__c q = new Quotation__c();
   q.COpportunity__c = oppty.id;
   q.Submit_for_review__c =TRUE;
   q.CostSheet__c =costSheet.id;
   q.Final__c =TRUE;
   insert q;
   
   Blob b = Blob.valueOf('Test Data');  
   Attachment attachment = new Attachment();  
   attachment.ParentId = q.id;  
   attachment.Name = 'Test Attachment for Parent';  
   attachment.Body = b;  
   insert(attachment);
  
   ApexPages.currentPage().getParameters().put('qid',q.id);
   QuoteEmail qe = new QuoteEmail();
   qe.cemail = 'aphidas@aphidas.com';
   qe.sendEmail();
   q.Final__c =FALSE;
   update q;
   qe.sendEmail();
   
 }
}