wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Gross_Margin__c.field-meta.xml
<CustomField>
    <fullName>Gross_Margin__c</fullName>
    <label>Gross Margin (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Labour_cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_cost__c</fullName>
    <label>Labour cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Material Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/CostSheet__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>CostSheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/CostSheet__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comments (if any)</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>CostSheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_sales_ratio__c.field-meta.xml
<CustomField>
    <fullName>Cost_sales_ratio__c</fullName>
    <formula>Total_Cost_TC__c  /  Sales_value_for_Quotation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost sales ratio (TC/SVQ)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Amount__c</fullName>
    <label>Sales Value as per pricing policy (SVP)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Contents__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Contents__c</fullName>
    <label>Cost Sheet Contents</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Preparation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Preparation_Date__c</fullName>
    <label>Cost Sheet Preparation Date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Version__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Version__c</fullName>
    <label>Cost Sheet Version</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <formula>Discount_amount_if_any__c / Cost_Sheet_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount in cost sheet (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Discount_amount_if_any__c.field-meta.xml
<CustomField>
    <fullName>Discount_amount_if_any__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Discount/Upselling amount (if any)</description>
    <label>Discount amount (if any)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Gross_Margin__c.field-meta.xml
<CustomField>
    <fullName>Gross_Margin__c</fullName>
    <formula>( Sales_value_for_Quotation__c  -  Total_Cost_TC__c  )  /  Sales_value_for_Quotation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Margin (SVQ-TC)/SVQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Labour_Cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cost__c</fullName>
    <label>Labour Cost (L)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Material Cost (M)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Other_Cost__c.field-meta.xml
<CustomField>
    <fullName>Other_Cost__c</fullName>
    <label>Other Costs (O)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Upsell_amount_if_any__c.field-meta.xml
<CustomField>
    <fullName>Upsell_amount_if_any__c</fullName>
    <label>Upsell amount (if any)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/classes/wr_CostSheet.cls
public with sharing class wr_CostSheet {

    Public CostSheet__c  cs{get; set;}
    public Attachment tAttachment{get;set;}
    public ID cid {get; set;}
    public wr_CostSheet(ApexPages.StandardController controller)
    {
       cs = new  CostSheet__c();
       cs.COpportunity__c = ApexPages.currentPage().getParameters().get('oppid');
       this.tAttachment = new Attachment();  
    }
   public pagereference csave()
   {
      try
      {
             
             CostSheet__c c = new CostSheet__c();
             c.Comment_if_any__c = cs.Comment_if_any__c;
             c.COpportunity__c = cs.COpportunity__c;
             c.CurrencyIsoCode = cs.CurrencyIsoCode;
             c.Labour_Cost__c = cs.Labour_Cost__c;
             c.Material_Cost__c = cs.Material_Cost__c;
             c.Other_cost__c = cs.Other_cost__c;
             //c.Total_cost__c= cs.Total_cost__c;
             c.Discount_amount_if_any__c = cs.Discount_amount_if_any__c;
             c.Upsell_amount_if_any__c = cs.Upsell_amount_if_any__c;
             c.Cost_Sheet_Amount__c =cs.Cost_Sheet_Amount__c; // selling price
             //c.Gross_Margin__c = cs.Gross_Margin__c;
            // c.Cost_sales_ratio__c = cs.Cost_sales_ratio__c; 
              // c.Discount__c = cs.Discount__c;
              c.Cost_Sheet_Preparation_Date__c =cs.Cost_Sheet_Preparation_Date__c;
              c.Cost_Sheet_Contents__c = cs.Cost_Sheet_Contents__c;
              Integer count = [select count() from CostSheet__c where COpportunity__c=:cs.COpportunity__c];
              if(count ==0)
              {
                 c.Cost_Sheet_Version__c ='V'+1;
              }
              else
              {
                 integer n =  count +1;
                 c.Cost_Sheet_Version__c ='V'+n;
              }
              if(tAttachment.Name!=null)
              //if(attname !=null)
              {
                    insert c;
                    cid  = c.id;
                    doUploadFile(c.ID);
              }
              else
              {
                   ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Please attach the file.');
                   ApexPages.addMessage(myMsg);
                   return null;
              }
      }
      
      catch(Exception e)
      {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
        ApexPages.addMessage(myMsg);
        return null;
      }
      PageReference pg = new PageReference('/'+cid);
      return pg;
   }
   public void doUploadFile(ID csqid)
   {
        List<Attachment> att = new List<Attachment >();
        Attachment a = this.tAttachment.clone(false, true, false, false);
        a.OwnerId = UserInfo.getUserId();
        //record attachment associated with
        a.ParentId = csqid;
        att.add(a);
        //clear body of uploaded file to remove from view state
        this.tAttachment.Body = null;
        //create the attachment
        try{Database.Insert(att);}
         catch(exception ex){
       
       }
    }
    
}