wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIS</fullName>
            </value>
            <value>
                <fullName>Dubai - APS/RE</fullName>
            </value>
            <value>
                <fullName>Dubai - Oilfield</fullName>
            </value>
            <value>
                <fullName>Iraq</fullName>
            </value>
            <value>
                <fullName>NAI</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Saudi</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/CSRDecisionOnBid__c.field-meta.xml
<CustomField>
    <fullName>CSRDecisionOnBid__c</fullName>
    <label>CSR&apos;s Decision on Bid</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Delivery_due_date_as_per_Customer_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_due_date_as_per_Customer_Order__c</fullName>
    <label>Delivery due date as per Customer Order</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/PO_handed_over_to_contract__c.field-meta.xml
<CustomField>
    <fullName>PO_handed_over_to_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO handed over to contract</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/PO_Attachments__c.object-meta.xml
<CustomObject>
    <label>PO Attachments</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>PO Attachments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Assign_Contract_Representative__c.field-meta.xml
<CustomField>
    <fullName>Assign_Contract_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign Contract Representative</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Contracts Manager</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Contracts Representative</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Bedford - Head of Tendering</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Bedford - Tendering Rep</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Barton - Tendering Rep</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>UK CSR+TM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Barton - Head of Tendering</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PO_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/comments_if_any__c.field-meta.xml
<CustomField>
    <fullName>comments_if_any__c</fullName>
    <label>Comments from Tendering</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Customer_document_reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_document_reference__c</fullName>
    <label>Customer document reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Delivery_due_date_as_per_Customer_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_due_date_as_per_Customer_Order__c</fullName>
    <label>Delivery due date as per Customer Order</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Info_clarification_reqd_from_customer__c.field-meta.xml
<CustomField>
    <fullName>Info_clarification_reqd_from_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Info/clarifn. reqd from customer by Tendering</description>
    <label>Clarifn. reqd from customer by Tendering</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>PO Attachments</relationshipLabel>
    <relationshipName>PO_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>Total amount as per Customer Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/PO_handed_over_to_contract__c.field-meta.xml
<CustomField>
    <fullName>PO_handed_over_to_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO handed over to Contract by Tendering</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/Test_weir_poattachments.cls
@isTest(SeeAllData = true)
private class  Test_weir_poattachments{    
    
    static testMethod void UnitTest() {

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        UserRole r = [select Id from userrole where 
        Name = 'Contracts Manager' or 
        Name = 'Contracts Representative'        
        limit 1];
 
        User u = [select Id,Business_Unit__c from user where userroleId =: r.Id limit 1];

        COpportunity__c Opp = new COpportunity__c(Business_Unit__c = 'Oman',CSRDecisionOnBid__c = 'YES');
        insert Opp;
        
        PO_Attachments__c poa = new PO_Attachments__c(
        Assign_Contract_Representative__c = u.Id,
        Customer_document_reference__c = 'TEST1234567890',
        Opportunity__c = opp.Id,
        PO_Amount__c = 100,
        Info_clarification_reqd_from_customer__c = false,
        PO_handed_over_to_contract__c = false,
        comments_if_any__c = 'testcom',
        Delivery_due_date_as_per_Customer_Order__c = system.today()
        
        );
        insert poa;
        
        Blob b = Blob.valueOf('Test Data');  
        Attachment attachment = new Attachment();  
        attachment.ParentId = poa.id;  
        attachment.Name = 'Test Attachment for Parent';  
        attachment.Body = b;  
        insert(attachment);
        
        ApexPages.StandardController std = new ApexPages.StandardController(poa);
        PageReference pageRef = Page.weir_poattachments;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', poa.id);
        ApexPages.currentPage().getParameters().put('CF00Ng0000000boAK_lkid', opp.Id);
        weir_poattachments  cont = new weir_poattachments (std);
        cont.tAttachment = Attachment;
        cont.csave();
        

    }
}