wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Movex_CO_No__c.field-meta.xml
<CustomField>
    <fullName>Movex_CO_No__c</fullName>
    <label>ERP CO No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/CostSheet__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>CostSheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/CostSheet__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comments (if any)</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>CostSheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comment if any</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/CostSheet__c.field-meta.xml
<CustomField>
    <fullName>CostSheet__c</fullName>
    <label>Cost Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.COpportunity__c</field>
            <operation>equals</operation>
            <valueField>CostSheet__c.COpportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostSheet__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Movex_Co_No__c.field-meta.xml
<CustomField>
    <fullName>Movex_Co_No__c</fullName>
    <label>ERP CO No.</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Movex_quotation_docs_serial_no__c.field-meta.xml
<CustomField>
    <fullName>Movex_quotation_docs_serial_no__c</fullName>
    <description>Movex Quotation Reference</description>
    <label>Customer Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Quotation_version__c.field-meta.xml
<CustomField>
    <fullName>Quotation_version__c</fullName>
    <label>Quotation version</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Submit_for_review__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for review</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/wr_Quotation.cls
public with sharing class wr_Quotation 
{
    Public Quotation__c  q {get; set;}
    public Attachment tAttachment{get;set;}
    public ID qid {get; set;}
    public wr_Quotation(ApexPages.StandardController controller) 
    {
       q = new   Quotation__c ();
       q.COpportunity__c = ApexPages.currentPage().getParameters().get('oppid');
       this.tAttachment = new Attachment();
    }
   public pagereference csave()
   {
      try
      {
         
        
             Quotation__c  c = new Quotation__c();
             c.CurrencyIsoCode = q.CostSheet__r.CurrencyIsoCode;
             c.COpportunity__c = q.COpportunity__c;
             c.CostSheet__c =q.CostSheet__c;
             c.Movex_Co_No__c =q.Movex_Co_No__c;
             c.Movex_quotation_docs_serial_no__c =q.Movex_quotation_docs_serial_no__c;
             c.Comment_if_any__c = q.Comment_if_any__c;
             c.Submit_for_review__c = q.Submit_for_review__c;
             
             Integer count = [select count() from Quotation__c where COpportunity__c=:q.COpportunity__c];
             if(count ==0)
             {
              c.Quotation_version__c ='V'+1;
             }
             else
             {
                  integer n =  count +1;
                  c.Quotation_version__c ='V'+n;
             }
         if(tAttachment.Name!=null)
         {
             insert c;
             qid  = c.id;
             doUploadFile(c.ID);
          }
          else
          {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Please attach the file.');
            ApexPages.addMessage(myMsg);
            return null;
          }
      }
      catch(Exception e)
      {
          ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
          ApexPages.addMessage(myMsg);
          return null;
      }
      PageReference pg = new PageReference('/'+qid);
      return pg;
   }
   public void doUploadFile(ID csqid)
   {
        List<Attachment> att = new List<Attachment >();
        Attachment a = this.tAttachment.clone(false, true, false, false);
        a.OwnerId = UserInfo.getUserId();
        //record attachment associated with
        a.ParentId = csqid;
        att.add(a);
        //clear body of uploaded file to remove from view state
        this.tAttachment.Body = null;
        //create the attachment
       try{Database.Insert(att);}
       catch(exception ex){
       
       }
 
    }

}