wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Bid/No Bid</fullName>
            </value>
            <value>
                <fullName>Approved for Tendering</fullName>
            </value>
            <value>
                <fullName>Quotation under compilation</fullName>
            </value>
            <value>
                <fullName>Tender Under Review</fullName>
            </value>
            <value>
                <fullName>Tender Under Approval</fullName>
            </value>
            <value>
                <fullName>Approved, Make Quotation ready for submitial</fullName>
            </value>
            <value>
                <fullName>Quote Ready for Submital</fullName>
            </value>
            <value>
                <fullName>Quote Submitted to Customer</fullName>
            </value>
            <value>
                <fullName>Customer Contacted for Submitted quote</fullName>
            </value>
            <value>
                <fullName>Quotation under clarification with Customer</fullName>
            </value>
            <value>
                <fullName>PO received</fullName>
            </value>
            <value>
                <fullName>PO Under Clarification</fullName>
            </value>
            <value>
                <fullName>PO handed over to Contract</fullName>
            </value>
            <value>
                <fullName>PO under Review with Contract</fullName>
            </value>
            <value>
                <fullName>PO Approved by Contract</fullName>
            </value>
            <value>
                <fullName>Customer order acknowledged</fullName>
            </value>
            <value>
                <fullName>PO handover to Planning</fullName>
            </value>
            <value>
                <fullName>Job handover to Operations</fullName>
            </value>
            <value>
                <fullName>Job done awaiting contracts sign-off</fullName>
            </value>
            <value>
                <fullName>Job ready for Delivery</fullName>
            </value>
            <value>
                <fullName>job delivered</fullName>
            </value>
            <value>
                <fullName>Opportunity closed</fullName>
            </value>
            <value>
                <fullName>Quote accepted but PO awaited</fullName>
            </value>
            <value>
                <fullName>Customer notified of a Completed Job</fullName>
            </value>
            <value>
                <fullName>Invoicing onhold</fullName>
            </value>
            <value>
                <fullName>Job invoiced in movex</fullName>
            </value>
            <value>
                <fullName>Partial Collected</fullName>
            </value>
            <value>
                <fullName>Fully Collected</fullName>
            </value>
            <value>
                <fullName>Invoice sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Quote_Submitted_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Quote_Submitted_to_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted quote to customer</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/QuoteEmail.cls
public with sharing class QuoteEmail 
{

    public String cemail {get; set;}
    public String oppid {get; set;}
    public String quotationname  {get; set;}
    public String semail {get; set;}
    public String subject{get; set;}
    public String body{get; set;}
    public ID Qid;
    public QuoteEmail() 
    {
      
       body ='';
       Qid= ApexPages.currentPage().getParameters().get('qid');  
       oppid = ApexPages.currentPage().getParameters().get('oppid');
       quotationname = ApexPages.currentPage().getParameters().get('qname');
       String userName = UserInfo.getUserName();
       User activeUser = [Select Email From User where Username = : userName limit 1];
       semail = activeUser.Email;
       subject = 'Quotation (Our Ref:'+oppid+'/'+quotationname+')';
    }
    public PageReference sendEmail()
    {
     try
     {
        if(!Pattern.matches('[a-zA-Z0-9._-]+@[a-zA-Z]+.[a-zA-Z]{2,4}', cemail))
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please provide valid email address.'));
            return null; 
        }
        else
        {
           Quotation__c qfinal = [select id,COpportunity__r.status__c, final__c from Quotation__c where id=:Qid limit 1];
           if(qfinal.final__c ==true && qfinal.COpportunity__r.status__c=='Quote Ready for Submital')
           {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();  
                String[] toAddresses = new String[] {cemail};  
                String[] ccAddresses = new String[] {semail};  
                mail.setToAddresses(toAddresses);  
                mail.setCcAddresses(ccAddresses);  
                mail.setReplyTo(cemail);  
                mail.setSenderDisplayName(UserInfo.getUseremail()); 
                mail.setSubject(subject);  
                mail.setBccSender(false);  
                mail.setUseSignature(true);  
                mail.setPlainTextBody(body);  
                //mail.setHtmlBody(‘<b> This is HTML body </b>’ );  
                List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();  
                for (Attachment a : [select Name, Body, BodyLength from Attachment where ParentId = :Qid])
                {  
                     Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();  
                     efa.setFileName(a.Name);  
                     efa.setBody(a.Body);  
                     fileAttachments.add(efa);  
                    //mail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});  
                }  
                mail.setFileAttachments(fileAttachments);  
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                qfinal.Quote_Submitted_to_Customer__c =true;
                update qfinal;
              }
              else
              {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Quotation must be approved before sending toCustomer.'));
                return null; 
              }
           }   
         } 
     catch(DMLException e) 
     {
     }    
     return new PageReference('javascript:self.close()'); 
  }

}