wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIS</fullName>
            </value>
            <value>
                <fullName>Dubai - APS/RE</fullName>
            </value>
            <value>
                <fullName>Dubai - Oilfield</fullName>
            </value>
            <value>
                <fullName>Iraq</fullName>
            </value>
            <value>
                <fullName>NAI</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Saudi</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/CSRDecisionOnBid__c.field-meta.xml
<CustomField>
    <fullName>CSRDecisionOnBid__c</fullName>
    <label>CSR&apos;s Decision on Bid</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Labour_cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_cost__c</fullName>
    <label>Labour cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Material Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/CostSheet__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>CostSheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/CostSheet__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comments (if any)</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>CostSheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Amount__c</fullName>
    <label>Sales Value as per pricing policy (SVP)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Cost_Sheet_Preparation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Preparation_Date__c</fullName>
    <label>Cost Sheet Preparation Date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Discount_amount_if_any__c.field-meta.xml
<CustomField>
    <fullName>Discount_amount_if_any__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Discount/Upselling amount (if any)</description>
    <label>Discount amount (if any)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Labour_Cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cost__c</fullName>
    <label>Labour Cost (L)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Material_Cost__c</fullName>
    <label>Material Cost (M)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/fields/Other_Cost__c.field-meta.xml
<CustomField>
    <fullName>Other_Cost__c</fullName>
    <label>Other Costs (O)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/Comment_if_any__c.field-meta.xml
<CustomField>
    <fullName>Comment_if_any__c</fullName>
    <label>Comment if any</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/CostSheet__c.field-meta.xml
<CustomField>
    <fullName>CostSheet__c</fullName>
    <label>Cost Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.COpportunity__c</field>
            <operation>equals</operation>
            <valueField>CostSheet__c.COpportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostSheet__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Movex_quotation_docs_serial_no__c.field-meta.xml
<CustomField>
    <fullName>Movex_quotation_docs_serial_no__c</fullName>
    <description>Movex Quotation Reference</description>
    <label>Customer Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Submit_for_review__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for review</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/FinalUpdate_Test.cls
@isTest
private class  FinalUpdate_Test{
    static Quotation__c setupData(){   
        COpportunity__c Opp = new COpportunity__c(Business_Unit__c = 'Oman',CSRDecisionOnBid__c = 'YES');
        insert Opp;
        CostSheet__c costSheet = new CostSheet__c(Comment_if_any__c = 'test', discount_amount_if_any__c = 100,COpportunity__c = opp.Id,Labour_Cost__c = 100, Material_Cost__c= 100, Other_Cost__c = 100,Cost_Sheet_Amount__c = 100, Cost_Sheet_Preparation_Date__c = system.today());
        insert costSheet;
        Quotation__c Quotation = new Quotation__c(Final__c = false, Submit_for_review__c=true, COpportunity__c = Opp.Id, CostSheet__c  = costSheet.Id, Movex_quotation_docs_serial_no__c = '123');
        insert Quotation; 
        return Quotation;
    }
    
    static testMethod void UnitTest() {      
        Quotation__c Quotation = setupData(); 
        Quotation.Final__c = true;
        update Quotation;
    }
}