wier/force-app/main/default/objects/Object_With_Query__mdt/Object_With_Query__mdt.object-meta.xml
<CustomObject>
    <label>Object With Query</label>
    <pluralLabel>Object With Query</pluralLabel>
</CustomObject>

wier/force-app/main/default/objects/Object_With_Query__mdt/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <label>Query String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

wier/force-app/main/default/objects/report_filter__mdt/report_filter__mdt.object-meta.xml
<CustomObject>
    <label>report filter</label>
    <pluralLabel>report filters</pluralLabel>
</CustomObject>

wier/force-app/main/default/objects/report_filter__mdt/fields/filter_string__c.field-meta.xml
<CustomField>
    <fullName>filter_string__c</fullName>
    <label>filter string</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/report_filter__mdt/fields/Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Report_ID__c</fullName>
    <label>Report ID</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/classes/dashboardExt.cls
public class dashboardExt {
    
    public map<string,string> filtermap{set;get;}
    public map<string,list<object>> listofObject {set;get;}
    public dashboardExt(ApexPages.StandardController controller) {
        string Accid = apexpages.currentpage().getparameters().get('id') ;
       // list<report_filter__mdt> reportfilterlist = [select filter_string__c,Report_ID__c from report_filter__mdt];
        filtermap = new map<string,string>();
        for(report_filter__mdt rf : [select filter_string__c,Report_ID__c from report_filter__mdt]){
            string filterstring = rf.filter_string__c;
            filterstring = filterstring.replace('AccId',Accid);
            filtermap.put(rf.Report_ID__c,filterstring);
        }
        //list<Object_With_Query__mdt> objectlist = [select name,Query_String__c from Object_With_Query__mdt];
        listofObject = new map<string,list<object>>();
        for(Object_With_Query__mdt oq: [select MasterLabel,Query_String__c from Object_With_Query__mdt]){
            listofObject.put(oq.MasterLabel, new list<object>());
            listofObject.get(oq.MasterLabel).addall(database.query(oq.Query_String__c));

        }
        
    }

}