wier/force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <label>Call/Visit Report</label>
    <nameField>
        <displayFormat>CID-{0000000000}</displayFormat>
        <label>Call Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call/Visit Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Call_Report__c/fields/Attendee1__c.field-meta.xml
<CustomField>
    <fullName>Attendee1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call/Visit Report (Attendee1)</relationshipLabel>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Call_Visit_date__c.field-meta.xml
<CustomField>
    <fullName>Call_Visit_date__c</fullName>
    <label>Call/Visit date</label>
    <type>DateTime</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Communication_type__c.field-meta.xml
<CustomField>
    <fullName>Communication_type__c</fullName>
    <description>Communication type</description>
    <label>Communication type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Personal visit</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Contacted_Spoken__c.field-meta.xml
<CustomField>
    <fullName>Contacted_Spoken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacted &amp; Spoken</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/classes/triggerParentCallVisit_TestController.cls
@isTest
private class triggerParentCallVisit_TestController
{
    static testMethod void triggerParentCallVisit_Testmethod()
    {
         Profile p = [SELECT Id FROM Profile WHERE Name='CSR']; 
         UserRole r = [ Select id from UserRole where Name='Customer Service Representative'];
         User u1 = new User(Alias = 'safddsfs', Email='newusegdr@testorg.com', 
         EmailEncodingKey='UTF-8', LastName='fsdggdg', LanguageLocaleKey='en_US', 
         LocaleSidKey='en_US', ProfileId = p.Id, UserRoleID = r.id,
         TimeZoneSidKey='America/Los_Angeles', UserName='newusergdgg@testorg.com');
         
         System.RunAs(u1)
         {
             Account ac = new Account(name='TestAccount');
             ac.Customer_Service_Representative__c = UserInfo.getUserId();
             insert ac;
             Contact con = new Contact();
             con.Lastname ='TestLast';
             con.Accountid = ac.id;
             insert con;
             Call_Report__c c = new Call_Report__c();
             c.Call_Visit_date__c = system.today();
             c.Customer__c =ac.id;
             c.Attendee1__c = con.id;
             c.Communication_type__c ='Telephone';
             c.Contacted_Spoken__c =TRUE;
             insert c;
             
        }
     }
}