wier/force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <label>Call/Visit Report</label>
    <nameField>
        <displayFormat>CID-{0000000000}</displayFormat>
        <label>Call Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call/Visit Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Call_Report__c/fields/Call_Visit_date__c.field-meta.xml
<CustomField>
    <fullName>Call_Visit_date__c</fullName>
    <label>Call/Visit date</label>
    <type>DateTime</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Communication_type__c.field-meta.xml
<CustomField>
    <fullName>Communication_type__c</fullName>
    <description>Communication type</description>
    <label>Communication type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Personal visit</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Contacted_Spoken__c.field-meta.xml
<CustomField>
    <fullName>Contacted_Spoken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacted &amp; Spoken</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/RFQ__c.object-meta.xml
<CustomObject>
    <label>RFQ/PO</label>
    <nameField>
        <displayFormat>WID-{00000000}</displayFormat>
        <label>RFQ/PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQ/PO</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/RFQ__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Status__c</field>
            <operation>notEqual</operation>
            <value>Suspended</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>RFQ1</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Customer_Acknowledgement_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acknowledgement_Name__c</fullName>
    <description>Send acknowledgement to</description>
    <label>Name Of The Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Customer_s_reference_in_RFQ__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_reference_in_RFQ__c</fullName>
    <label>Ref. (if any) in customer communication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Date_on_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Date_on_Enquiry__c</fullName>
    <label>Date of  receipt from Customer</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/classes/Trigger_Numbercallreportupdate_TestClass.cls
@isTest
private class Trigger_Numbercallreportupdate_TestClass 
{
    static testMethod void myUnitTest() 
    {
         Profile p = [SELECT Id FROM Profile WHERE Name='CSR']; 
         UserRole r = [ Select id from UserRole where Name='Customer Service Representative'];
         User u1 = new User(Alias = 'safddsfs', Email='newusegdr@testorg.com', 
         EmailEncodingKey='UTF-8', LastName='fsdggdg', LanguageLocaleKey='en_US', 
         LocaleSidKey='en_US', ProfileId = p.Id, UserRoleID = r.id,
         TimeZoneSidKey='America/Los_Angeles', UserName='newusergdgg@testorg.com');
         
         System.RunAs(u1)
         {
             Account ac = new Account(name='TestAccount');
             ac.Customer_Service_Representative__c = UserInfo.getUserId();
             insert ac;
             Call_Report__c c = new Call_Report__c();
             c.Call_Visit_date__c = system.today();
             c.Customer__c =ac.id;
             c.Communication_type__c ='Telephone';
             c.Contacted_Spoken__c =TRUE;
             insert c;
             Task ta =  new Task();
             ta.Subject ='call';
            // ta.Owner = u1[0].id;
             ta.status = 'Open';
             ta.Priority = 'High';
             ta.Assigned_To_CRM_User__c ='Test@test.com';
             ta.ActivityDate = system.today();
             ta.WhatID = c.id;
             insert ta;
             
             
            
             RFQ__c rfq = new RFQ__c();
             rfq.Account__c = ac.id;
             rfq.Date_on_Enquiry__c = system.today();
             rfq.Customer_Acknowledgement_Name__c = 'Testing';
             rfq.Customer_s_reference_in_RFQ__c ='Testing2';
             insert rfq;
            
             Apexpages.standardController newController = new Apexpages.StandardController(rfq);
        }
      
      }
}