wier/force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <label>Call/Visit Report</label>
    <nameField>
        <displayFormat>CID-{0000000000}</displayFormat>
        <label>Call Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call/Visit Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Call_Report__c/fields/Call_Visit_date__c.field-meta.xml
<CustomField>
    <fullName>Call_Visit_date__c</fullName>
    <label>Call/Visit date</label>
    <type>DateTime</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Communication_type__c.field-meta.xml
<CustomField>
    <fullName>Communication_type__c</fullName>
    <description>Communication type</description>
    <label>Communication type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Personal visit</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Contacted_Spoken__c.field-meta.xml
<CustomField>
    <fullName>Contacted_Spoken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacted &amp; Spoken</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/Call_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Quotation_submittal_date__c.field-meta.xml
<CustomField>
    <fullName>Quotation_submittal_date__c</fullName>
    <label>Quotation submittal due date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Win_Probability__c.field-meta.xml
<CustomField>
    <fullName>Win_Probability__c</fullName>
    <label>Win probability (%)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/classes/Trigger_UpdateLeadStatus_TestClass.cls
@isTest
private class Trigger_UpdateLeadStatus_TestClass 
{
    static testMethod void myUnitTest() 
    {
       
        Lead l = new Lead();
        l.lastname = 'Testname';
        l.status = 'Open';
        l.Company ='Aphidas';
        insert l;
        
        COpportunity__c oppty = new COpportunity__c();
        //oppty.Win_Probability__c = 90;
       // oppty.OwnerId = acc.Customer_Service_Representative__c;
        oppty.Quotation_submittal_date__c = System.today();
        insert oppty;
        
        Call_Report__c c = new Call_Report__c();
        c.Call_Visit_date__c = system.today();
        c.Lead__c =l.id;
        c.Communication_type__c ='Telephone';
        c.Contacted_Spoken__c =TRUE;
        insert c; 
        Call_Report__c copp = new Call_Report__c();
        copp.Call_Visit_date__c = system.today();
        copp.Opportunity__c =oppty.id;
        copp.Communication_type__c ='Telephone';
        copp.Contacted_Spoken__c =TRUE;
        insert copp ; 
      
    }
}