wier/force-app/main/default/objects/Potential_revenue_for_the_year__c/Potential_revenue_for_the_year__c.object-meta.xml
<CustomObject>
    <label>Potential revenue for the year</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Potential revenue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential revenue for the year</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Potential_revenue_for_the_year__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Potential revenue for the year</relationshipLabel>
    <relationshipName>Potential_revenue_for_the_year</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Potential_revenue_for_the_year__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/classes/Test_triggerParentPotential.cls
@isTest(SeeALLData = true)
private class  Test_triggerParentPotential{
    static void setupData(){ 
    
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        UserRole r = [select Id from userrole where 
        Name = 'Customer Service Representative' or 
        Name = 'Head of Sales' or 
        Name = 'Non DXB Iraq Team member' or 
        Name = 'Non DXB Non Iraq Team member' or 
        Name = 'Senior Customer Services Representative - 1' or 
        Name = 'Senior Customer Services Representative - 2' or 
        Name = 'Sub Customer Service Representative - 1' or 
        Name = 'Sub Customer Service Representative - 2' or 
        Name = 'Iraq Customer Service Representative'         
        limit 1];

 
        User u = [select Id,Business_Unit__c from user where userroleId =: r.Id limit 1];
        
            
        Account Acc = new Account(Name = 'TesTACC',Business_Unit__c = u.Business_Unit__c ,Customer_Service_Representative__c = u.Id);insert Acc;
        Contact Con = new Contact(LastName = 'TestCon',AccountId = Acc.Id);insert con;
        con.FirstName = 'Test';
        update con;
        
        Potential_revenue_for_the_year__c pry = new Potential_revenue_for_the_year__c(
        Customer__c = Acc.Id
        );
        
        insert pry;
        pry.Year__c = '2015';
        update pry;
        
    }
    
    static testMethod void UnitTest() {      
        setupData();        
    }
}