wier/force-app/main/default/objects/Potential_revenue_for_the_year__c/Potential_revenue_for_the_year__c.object-meta.xml
<CustomObject>
    <label>Potential revenue for the year</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Potential revenue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential revenue for the year</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Potential_revenue_for_the_year__c/fields/APS__c.field-meta.xml
<CustomField>
    <fullName>APS__c</fullName>
    <label>APS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

wier/force-app/main/default/objects/Potential_revenue_for_the_year__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Potential revenue for the year</relationshipLabel>
    <relationshipName>Potential_revenue_for_the_year</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/classes/triggerParentPotential_TestController.cls
@isTest
private class triggerParentPotential_TestController
{
    static testMethod void triggerParentPotential_Testmethod()
    {
         Profile p = [SELECT Id FROM Profile WHERE Name='CSR']; 
         UserRole r = [ Select id from UserRole where Name='Customer Service Representative'];
         User u1 = new User(Alias = 'safddsfs', Email='newusegdr@testorg.com', 
         EmailEncodingKey='UTF-8', LastName='fsdggdg', LanguageLocaleKey='en_US', 
         LocaleSidKey='en_US', ProfileId = p.Id, UserRoleID = r.id,
         TimeZoneSidKey='America/Los_Angeles', UserName='newusergdgg@testorg.com');
         
         System.RunAs(u1)
         {
             Account ac = new Account(name='TestAccount');
             ac.Customer_Service_Representative__c = UserInfo.getUserId();
             insert ac;
             Contact con = new Contact();
             con.Lastname ='TestLast';
             con.Accountid = ac.id;
             insert con;
             
             Potential_revenue_for_the_year__c pe = new Potential_revenue_for_the_year__c();
             pe.Customer__c = ac.id;
             pe.APS__c = 4000;
             insert pe;
             pe.APS__c = 5000;
             Update pe;
             
        }
     }
}