wier/force-app/main/default/objects/Contract_Checklst__c/Contract_Checklst__c.object-meta.xml
<CustomObject>
    <label>Contract Checklist</label>
    <nameField>
        <label>Contract Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Assignee_status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_status__c</fullName>
    <label>Assignee status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Contract_Manager_requires_changes__c.field-meta.xml
<CustomField>
    <fullName>Contract_Manager_requires_changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Manager requires changes</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Final_Approval__c.field-meta.xml
<CustomField>
    <fullName>Final_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final contract manager approval</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Contract Checklists</relationshipLabel>
    <relationshipName>Contract_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/PO_Attachments__c.field-meta.xml
<CustomField>
    <fullName>PO_Attachments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Attachments</label>
    <referenceTo>PO_Attachments__c</referenceTo>
    <relationshipLabel>Contract Checklists</relationshipLabel>
    <relationshipName>Contract_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Require_Changes__c.field-meta.xml
<CustomField>
    <fullName>Require_Changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require Changes</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Submit_for_Contract_Manager_Approval__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_Contract_Manager_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Contract Manager Approval</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Tendering_Manager_Comments__c.field-meta.xml
<CustomField>
    <fullName>Tendering_Manager_Comments__c</fullName>
    <label>Contract Manager&apos;s Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Whether_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Whether_Applicable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Whether Applicable</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/PO_Attachments__c.object-meta.xml
<CustomObject>
    <label>PO Attachments</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>PO Attachments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>PO Attachments</relationshipLabel>
    <relationshipName>PO_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Quotation_ID__c.field-meta.xml
<CustomField>
    <fullName>Quotation_ID__c</fullName>
    <formula>Opportunity__r.Quotation_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quotation ID</label>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/wr_ContractCheckList.cls
public class wr_ContractCheckList 
{

    public Boolean requirechk { get; set;}
    public Boolean cmrequirechk { get; set;}
    public String profilename { get; set;}
    public Boolean submitforapproval { get; set;}
    public Boolean finlapproval { get; set;}
    public List<Contract_Checklst__c>  checklistresult{get;set;}
    public List<Contract_Checklst__c>  checkboxresult{get;set;}
    public List<Contract_Checklst__c>  checklistAddList {get;set;}
    public List<Contract_Checklst__c> checklistAddListnew {get;set;}
    public string oppid= ApexPages.currentPage().getParameters().get('oid');
    private final Contract_Checklst__c contCheck;
    Public String qry;
    public wr_ContractCheckList(ApexPages.StandardController controller) 
    {
       
        this.contCheck = (Contract_Checklst__c)controller.getRecord();
        User user = [select id, Profile.Name, Profile.PermissionsModifyAllData from User where id = :Userinfo.getUserId()];
        profilename  = user.Profile.Name;
        oppid= ApexPages.currentPage().getParameters().get('oid');
        checklistAddList= new List<Contract_Checklst__c>();
        if(!Test.isrunningTest())
        {
            qry = 'SELECT Name,PO_Attachments__c,PO_Attachments__r.Quotation_ID__c,S_No__c,Name__c,Final_Approval__c,Contract_Manager_requires_changes__c,Opportunity__c,Due_date__c,Assignee_status__c,Require_Changes__c,Submit_for_Contract_Manager_Approval__c,Tendering_Manager_Comments__c,Assigned_Status__c,Assignee_Comments__c,Whether_Applicable__c From Contract_Checklst__c WHERE Contract_Checklst__c.Opportunity__c= : oppid ORDER BY S_No__c ASC'; 
        }
        else
        {
         qry = 'SELECT Name,PO_Attachments__c,PO_Attachments__r.Quotation_ID__c,S_No__c,Name__c,Final_Approval__c,Contract_Manager_requires_changes__c,Opportunity__c,Due_date__c,Assignee_status__c,Require_Changes__c,Submit_for_Contract_Manager_Approval__c,Tendering_Manager_Comments__c,Assigned_Status__c,Assignee_Comments__c,Whether_Applicable__c From Contract_Checklst__c limit 1'; 
        }
        checklistresult= Database.query(qry);
        checklistAddList.add(new Contract_Checklst__c());
        
            requirechk =checklistresult[0].Require_Changes__c;
            submitforapproval  = checklistresult[0].Submit_for_Contract_Manager_Approval__c;
            finlapproval = checklistresult[0].Final_Approval__c;
            cmrequirechk = checklistresult[0].Contract_Manager_requires_changes__c;
        
        
    }
    
   Public  PageReference csave()
   {
     try 
       {
        String quotationId = [select id,Quotation_ID__c from PO_Attachments__c where id =:contCheck.PO_Attachments__c limit 1].Quotation_ID__c;
        Quotation__c Quot = !Test.isRunningTest()?[select id,Name,Final__c from Quotation__c where name =: quotationId limit 1]: [select id,Name,Final__c from Quotation__c Limit 1];
       
        
          Integer existinglistsize = checklistresult.size();
          Integer totalnewrecord =checklistAddList.size();
          if(requirechk ==TRUE)
              {
                checklistresult[0].Require_Changes__c =TRUE;
              }
              else
              {
               checklistresult[0].Require_Changes__c =false;
              }
              if(submitforapproval  ==TRUE)
              {
                    checklistresult[0].Submit_for_Contract_Manager_Approval__c =TRUE;  
              }
              else
              {
                    checklistresult[0].Submit_for_Contract_Manager_Approval__c =false;
              }
              if(cmrequirechk ==TRUE)
              {
                  checklistresult[0].Contract_Manager_requires_changes__c=TRUE;
              }
              else
              {
                  checklistresult[0].Contract_Manager_requires_changes__c=false;
              }
              if(finlapproval ==TRUE)
              {
                  checklistresult[0].Final_Approval__c =TRUE;
              }
              else
              {
               checklistresult[0].Final_Approval__c =false;
              }
              checklistAddListnew = new List<Contract_Checklst__c>();
          
          
          for(Integer i=0;i< totalnewrecord ;i++)
          {
              if(checklistAddList.get(i).Name__c!='')
              {
               Contract_Checklst__c chnew = new  Contract_Checklst__c();
               chnew.Name = 'Contract Checklist';
               chnew.Name__c = checklistAddList.get(i).Name__c;
               chnew.Assignee_status__c =checklistAddList.get(i).Assignee_status__c;
               chnew.Tendering_Manager_Comments__c =checklistAddList.get(i).Tendering_Manager_Comments__c;
               chnew.Assignee_Comments__c= checklistAddList.get(i).Assignee_Comments__c;
               chnew.Whether_Applicable__c = TRUE;
               chnew.S_No__c = existinglistsize + i;
               chnew.Opportunity__c = oppid;
               checklistAddListnew.add(chnew);
              }
              else
              {
               existinglistsize = existinglistsize -1;
              }
          }
        
          insert checklistAddListnew;
             
              if(Quot.Final__c == false)
              {
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Quote is not finalized'));
               return NULL;    
              }
              update checklistresult;
           
              
          
          //message = 'updated records Sucessfully';
        } 
        Catch (DMLException e) 
        {
            ApexPages.addMessages(e);
            return null;
        }
        //return null;
      return new PageReference('javascript:self.close()');
      
   }
   
   public void AddRow()
   {
        checklistAddList.add(new Contract_Checklst__c());
   }  
   
  public PageReference cancel() 
  {
    return new PageReference('/'+ApexPages.currentPage().getParameters().get('oid'));
  }

}