wier/force-app/main/default/objects/Contract_Checklst__c/Contract_Checklst__c.object-meta.xml
<CustomObject>
    <label>Contract Checklist</label>
    <nameField>
        <label>Contract Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Contract_Manager_requires_changes__c.field-meta.xml
<CustomField>
    <fullName>Contract_Manager_requires_changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Manager requires changes</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Final_Approval__c.field-meta.xml
<CustomField>
    <fullName>Final_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final contract manager approval</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Contract Checklists</relationshipLabel>
    <relationshipName>Contract_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/PO_Attachments__c.field-meta.xml
<CustomField>
    <fullName>PO_Attachments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Attachments</label>
    <referenceTo>PO_Attachments__c</referenceTo>
    <relationshipLabel>Contract Checklists</relationshipLabel>
    <relationshipName>Contract_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Require_Changes__c.field-meta.xml
<CustomField>
    <fullName>Require_Changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require Changes</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/Contract_Checklst__c/fields/Submit_for_Contract_Manager_Approval__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_Contract_Manager_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Contract Manager Approval</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Quotation_ID__c.field-meta.xml
<CustomField>
    <fullName>Quotation_ID__c</fullName>
    <label>Quotation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Quotation_submittal_date__c.field-meta.xml
<CustomField>
    <fullName>Quotation_submittal_date__c</fullName>
    <label>Quotation submittal due date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Win_Probability__c.field-meta.xml
<CustomField>
    <fullName>Win_Probability__c</fullName>
    <label>Win probability (%)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/CostSheet__c/CostSheet__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>CostSheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/CostSheet__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>CostSheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/PO_Attachments__c.object-meta.xml
<CustomObject>
    <label>PO Attachments</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>PO Attachments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>PO Attachments</relationshipLabel>
    <relationshipName>PO_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/PO_Attachments__c/fields/Quotation_ID__c.field-meta.xml
<CustomField>
    <fullName>Quotation_ID__c</fullName>
    <formula>Opportunity__r.Quotation_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quotation ID</label>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>QID-{000000000}</displayFormat>
        <label>QuotationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Quotation__c/fields/COpportunity__c.field-meta.xml
<CustomField>
    <fullName>COpportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/CostSheet__c.field-meta.xml
<CustomField>
    <fullName>CostSheet__c</fullName>
    <label>Cost Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.COpportunity__c</field>
            <operation>equals</operation>
            <valueField>CostSheet__c.COpportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostSheet__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Quotation__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/classes/wr_ContractCheckList_TestClass.cls
@isTest(seeAllData=True)
private class wr_ContractCheckList_TestClass
{  
  
   static testMethod void wr_ContractCheckList_TestClassmethod()
    {
    
      test.startTest();
       
        //User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        //EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        //LocaleSidKey='en_US', Role = 'Customer Service Representative', 
        //TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
       
        Profile prof = [Select id from Profile where  Name ='System Administrator'];
        User u = new User(Alias = 'sampath', Email='standarduser@testorg.com', 
       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = prof.id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='sampath@testorg.com');
       
      System.runAs(u) 
      {
           COpportunity__c oppty = new COpportunity__c();
           //oppty.Win_Probability__c = 90;
           oppty.Quotation_submittal_date__c = System.today();
           insert oppty;
           
           CostSheet__c  cost = new CostSheet__c ();
           cost.COpportunity__c = oppty.id;
           insert cost;
             
            Quotation__c quot = new Quotation__c();
            quot.CostSheet__c = cost.id;
            quot.COpportunity__c = oppty.id;
            quot.Final__c = TRUE;
            insert quot;     
            oppty.Quotation_ID__c = quot.name;
            update oppty;
              
            PO_Attachments__c PO = new PO_Attachments__c();
            PO.Opportunity__c   =oppty.id;
            insert PO;
            List<Contract_Checklst__c> listchklist = new List<Contract_Checklst__c>();
            for(integer i=0; i<1; i++) 
            {
                listchklist.add( new Contract_Checklst__c(PO_Attachments__c = PO.id,Opportunity__c= oppty.id,Assignee_Comments__c = 'TestingData',Require_Changes__c = TRUE));
            }
            insert listchklist;
       // checkList.Require_Changes__c = TRUE;
       // checkList.Submit_for_Contract_Manager_Approval__c =FALSE;
       // checkList.Final_Approval__c=FALSE;
       // checkList.Contract_Manager_requires_changes__c=FALSE;
       // insert checkList;
        
       
            ApexPages.StandardController con = new ApexPages.StandardController(listchklist[0]);
            ApexPages.currentPage().getParameters().put('id', oppty.id);  
            wr_ContractCheckList wrconCheckList = new wr_ContractCheckList(con); 
            
            wrconCheckList.submitforapproval=TRUE;
            wrconCheckList.cmrequirechk = TRUE;
            wrconCheckList.finlapproval=TRUE; 
            wrconCheckList.AddRow();
            wrconCheckList.cancel();
            wrconCheckList.csave();
            wrconCheckList.requirechk = TRUE;
            listchklist[0].Require_Changes__c =TRUE;
            update listchklist;
             wrconCheckList.csave();
          test.stoptest();
        
       }
     }

}