wier/force-app/main/default/objects/RFQ__c/RFQ__c.object-meta.xml
<CustomObject>
    <label>RFQ/PO</label>
    <nameField>
        <displayFormat>WID-{00000000}</displayFormat>
        <label>RFQ/PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQ/PO</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/RFQ__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Status__c</field>
            <operation>notEqual</operation>
            <value>Suspended</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>RFQ1</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Customer_Acknowledgement_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acknowledgement_Name__c</fullName>
    <description>Send acknowledgement to</description>
    <label>Name Of The Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Customer_s_reference_in_RFQ__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_reference_in_RFQ__c</fullName>
    <label>Ref. (if any) in customer communication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Date_on_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Date_on_Enquiry__c</fullName>
    <label>Date of  receipt from Customer</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/classes/Trigger_RFQToOpportunity_TestClass.cls
@isTest
private class Trigger_RFQToOpportunity_TestClass 
{
    static testMethod void myUnitTest() 
    {
         Profile p = [SELECT Id FROM Profile WHERE Name='CSR']; 
         UserRole r = [ Select id from UserRole where Name='Customer Service Representative'];
         User u1 = new User(Alias = 'weuetwet', Email='dfhdfhhfd@testorg.com', 
         EmailEncodingKey='UTF-8', LastName='hdfdhhfdh', LanguageLocaleKey='en_US', 
         LocaleSidKey='en_US', ProfileId = p.Id, UserRoleID = r.id,
         TimeZoneSidKey='America/Los_Angeles', UserName='newuhdfhdfhser@testorg.com');
         System.RunAs(u1)
         {
             Account ac = new Account(name='TestAccount');
             ac.Customer_Service_Representative__c = UserInfo.getUserId();
             insert ac;
            
             RFQ__c rfq = new RFQ__c();
             rfq.Account__c = ac.id;
             rfq.Date_on_Enquiry__c = system.today();
             rfq.Customer_Acknowledgement_Name__c = 'Testing';
             rfq.Customer_s_reference_in_RFQ__c ='Testing2';
             insert rfq;
            
             Apexpages.standardController newController = new Apexpages.StandardController(rfq);
        }
      
      }
}