wier/force-app/main/default/objects/RFQ__c/RFQ__c.object-meta.xml
<CustomObject>
    <label>RFQ/PO</label>
    <nameField>
        <displayFormat>WID-{00000000}</displayFormat>
        <label>RFQ/PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQ/PO</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/RFQ__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Status__c</field>
            <operation>notEqual</operation>
            <value>Suspended</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>RFQ1</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Customer_Acknowledgement_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acknowledgement_Name__c</fullName>
    <description>Send acknowledgement to</description>
    <label>Name Of The Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Email Address Of The Customer</label>
    <type>Email</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Date_on_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Date_on_Enquiry__c</fullName>
    <label>Date of  receipt from Customer</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>RFQ</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Not_available__c.field-meta.xml
<CustomField>
    <fullName>Not_available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer did not quote any Ref.</label>
    <type>Checkbox</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Received_From__c.field-meta.xml
<CustomField>
    <fullName>Received_From__c</fullName>
    <label>Received  from</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Tendering_Manager__c.field-meta.xml
<CustomField>
    <fullName>Tendering_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tendering Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Senior Tendering Rep</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Head of Tendering</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>UK CSR+TM</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Aberdeen Tendering Manager</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Dubai - Oilfield Head of Sales</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Tendering Manager - Abu Dhabi</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Baku - Head of Tendering</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RFQ</relationshipName>
    <type>Lookup</type>
</CustomField>

wier/force-app/main/default/objects/RFQ__c/fields/Time_of_Email_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Time_of_Email_Receipt__c</fullName>
    <label>Time of receiving RFQ/PO in email addres</label>
    <type>DateTime</type>
</CustomField>

wier/force-app/main/default/classes/Test_RFQToOpportunity.cls
@isTest(SeeALLData = true)
private class  Test_RFQToOpportunity{
    static void setupData(){ 
    
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        UserRole r = [select Id from userrole where 
        Name = 'Customer Service Representative' or 
        Name = 'Head of Sales' or 
        Name = 'Non DXB Iraq Team member' or 
        Name = 'Non DXB Non Iraq Team member' or 
        Name = 'Senior Customer Services Representative - 1' or 
        Name = 'Senior Customer Services Representative - 2' or 
        Name = 'Sub Customer Service Representative - 1' or 
        Name = 'Sub Customer Service Representative - 2' or 
        Name = 'Iraq Customer Service Representative'         
        limit 1];

 
        User u = [select Id,Business_Unit__c from user where userroleId =: r.Id limit 1];
        
        
        
            
        Account Acc = new Account(Name = 'TesTACC',Business_Unit__c = u.Business_Unit__c ,Customer_Service_Representative__c = u.Id);insert Acc;
        Contact Con = new Contact(LastName = 'TestCon',AccountId = Acc.Id);insert con;
        con.FirstName = 'Test';
        update con;
        
        Lead l = new Lead(LastName = 'Test Lead',
        Expected_Date_of_Input__c = system.today(),Expected_Value__c = 100, 
        Probability__c = 1, 
        LeadSource = 'Email',
        Revenue_Stream__c = 'APS',
        Type_of_Lead__c = 'Commissioning',
        Type_of_Customer__c = 'Competitor',
        industry = 'UAE',
        Strategic__c = 'Advanced Parts Solution',
        Company = 'Manjunath',
        Account_Name__c = Acc .Id);
        insert l;
        
        UserRole r1 = [select Id from userrole where 
        Name = 'Tendering Manager' or 
        Name = 'Head of Tendering'          
        limit 1];

 
        User u1 = [select Id,Business_Unit__c from user where userroleId =: r1.Id or alias = 'Durga' or alias ='Santhosh'  limit 1];
        
        
        RFQ__c rqc = new RFQ__c(Received_From__c = 'Test RQ',
        Date_on_Enquiry__c = system.today(),
        Time_of_Email_Receipt__c = system.now(),
        Account__c = Acc.Id,
        Tendering_Manager__c = u1.Id,
        Lead__c = l.Id,
        Not_available__c  = true,
        Customer_Acknowledgement_Name__c = 'Test Ack',
        Customer_Email__c = 'test@gmail.com');

        insert rqc;
        
        
    }
    
    static testMethod void UnitTest() {      
        setupData();        
    }
}