wier/force-app/main/default/objects/Sales_budget_for_the_year__c/Sales_budget_for_the_year__c.object-meta.xml
<CustomObject>
    <label>Sales budget for the year</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales budget for the year ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales budget for the year</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Sales_budget_for_the_year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales budget for the year</relationshipLabel>
    <relationshipName>Sales_budget_for_the_year</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Sales_budget_for_the_year__c/fields/First_Quarter_APS__c.field-meta.xml
<CustomField>
    <fullName>First_Quarter_APS__c</fullName>
    <label>First Quarter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

wier/force-app/main/default/classes/triggerParentSalesBudget_TestController.cls
@isTest
private class triggerParentSalesBudget_TestController
{
    static testMethod void triggerParentSalesBudget_Testmethod()
    {
         Profile p = [SELECT Id FROM Profile WHERE Name='CSR']; 
         UserRole r = [ Select id from UserRole where Name='Customer Service Representative'];
         User u1 = new User(Alias = 'safddsfs', Email='newusegdr@testorg.com', 
         EmailEncodingKey='UTF-8', LastName='fsdggdg', LanguageLocaleKey='en_US', 
         LocaleSidKey='en_US', ProfileId = p.Id, UserRoleID = r.id,
         TimeZoneSidKey='America/Los_Angeles', UserName='newusergdgg@testorg.com');
         
         System.RunAs(u1)
         {
             Account ac = new Account(name='TestAccount');
             ac.Customer_Service_Representative__c = UserInfo.getUserId();
             insert ac;
             Sales_budget_for_the_year__c sb = new Sales_budget_for_the_year__c();
             sb.Account__c = ac.id;
             sb.First_Quarter_APS__c = 4000;
             insert sb;
             sb.First_Quarter_APS__c = 5000;
             Update sb;
             
        }
     }
}