wier/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/Invoice_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Items</label>
    <nameField>
        <displayFormat>IN - {0000}</displayFormat>
        <label>Invoice Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Arabic_ID__c.field-meta.xml
<CustomField>
    <fullName>Arabic_ID__c</fullName>
    <label>Level 1 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Invoice__r.Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_10_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_10_Link__c</fullName>
    <label>Level 10 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_11_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_11_Link__c</fullName>
    <label>Level 11 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_12_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_12_Link__c</fullName>
    <label>Level 12 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_13_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_13_Link__c</fullName>
    <label>Level 13 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_14_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_14_Link__c</fullName>
    <label>Level 14 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_15_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_15_Link__c</fullName>
    <label>Level 15 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_16_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_16_Link__c</fullName>
    <label>Level 16 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_17_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_17_Link__c</fullName>
    <label>Level 17 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_18_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_18_Link__c</fullName>
    <label>Level 18 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_19_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_19_Link__c</fullName>
    <label>Level 19 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_20_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_20_Link__c</fullName>
    <label>Level 20 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_21_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_21_Link__c</fullName>
    <label>Level 21 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_22_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_22_Link__c</fullName>
    <label>Level 22 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_23_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_23_Link__c</fullName>
    <label>Level 23 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_2_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Link__c</fullName>
    <label>Level 2 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_3_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_3_Link__c</fullName>
    <label>Level 3 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_4_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_4_Link__c</fullName>
    <label>Level 4 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_5_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_5_Link__c</fullName>
    <label>Level 5 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_6_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_6_Link__c</fullName>
    <label>Level 6 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_7_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_7_Link__c</fullName>
    <label>Level 7 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_8_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_8_Link__c</fullName>
    <label>Level 8 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Level_9_Link__c.field-meta.xml
<CustomField>
    <fullName>Level_9_Link__c</fullName>
    <label>Level 9 Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Line_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Description__c</fullName>
    <label>Line Item Description</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Product_Detail_Arabic__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail_Arabic__c</fullName>
    <label>Product Detail Arabic</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Product_Detatil__c.field-meta.xml
<CustomField>
    <fullName>Product_Detatil__c</fullName>
    <label>Product Detatil</label>
    <type>TextArea</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Unit_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <label>VAT Rate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/classes/InvoiceArabic.cls
public class InvoiceArabic {
    public Id invoiceid {get;set;}
    public List<Invoice_Line_Items__c> lstCEERLines {get;set;}
    public List<Invoice_Line_Items__c> newlstCEERLines {get;set;}
    public String imageURL{get;set;}
    public String imageDeliverToURL{get;set;}
    public String imgge{get;set;}
    public boolean flag{get;set;}
    
	public InvoiceArabic(ApexPages.StandardController controller){
        //get record id
        invoiceid = controller.getId();
        
        List<Invoice__c> invoiceList = [Select id,Customer__c from Invoice__c where id =:invoiceid];
    
    	//imageURL='/servlet/servlet.FileDownload?file=00P1l0000033IO4';
    	//        imageDeliverToURL='/servlet/servlet.FileDownload?file=00P1l0000033IMX';
    	
    	imageURL='/servlet/servlet.FileDownload?file=';
        imageDeliverToURL='/servlet/servlet.FileDownload?file=';
        
    	List< Attachment  > documentList=[select Id,name from Attachment where
                                    Name='InvoiceTo.PNG' AND ParentId =: invoiceList.get(0).Customer__c LIMIT 1];
 		List< Attachment  > documentList1=[select Id,name from Attachment where
                                    Name='DeliverTo.PNG' AND ParentId =: invoiceList.get(0).Customer__c LIMIT 1];
            
        List<Document> docList = [SELECT Name,id FROM Document WHERE Name = 'Blank'];
        
    	if(documentList.size()>0){
      		imageURL=imageURL+documentList[0].id;
        } else{
            imageURL=imageURL+docList[0].id;
        }
        
        if(documentList1.size()>0){
      		imageDeliverToURL=imageDeliverToURL+documentList1[0].id;
            
        } else{
           imageDeliverToURL=imageDeliverToURL+docList[0].id;
        }
        
 	}
    
    public void getItems(){
        
        lstCEERLines = [Select name,Product_Detatil__c,Level_2_Link__c,Level_3_Link__c,Level_4_Link__c,Level_5_Link__c,
                        Level_6_Link__c,Level_7_Link__c,Level_8_Link__c,Level_9_Link__c,Level_10_Link__c,Level_11_Link__c,
                        Level_12_Link__c,Level_13_Link__c,Level_14_Link__c,Level_15_Link__c,Level_16_Link__c,Level_17_Link__c,
                        Level_18_Link__c,Level_19_Link__c,Level_20_Link__c,Level_21_Link__c,Level_22_Link__c,Level_23_Link__c,
                        Product_Code__c,Arabic_ID__c,Product_Detail_Arabic__c,Delivery_Date__c,VAT_Rate__c,Line__c,Line_Item_Description__c,
                        Quantity__c,Unit_Price__c,Total_Price__c from Invoice_Line_Items__c where Invoice__c=:invoiceid Order By Line__c];
        for(Invoice_Line_Items__c inv : lstCEERLines){
            //imgge = 
        }
    }
}