wier/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/Invoice_Line_Items__c/Invoice_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Items</label>
    <nameField>
        <displayFormat>IN - {0000}</displayFormat>
        <label>Invoice Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Invoice_Line_Items__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Invoice__r.Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

wier/force-app/main/default/classes/InvoiceArabicTest.cls
@isTest(seeAllData=true)
public class InvoiceArabicTest {
	static testMethod void testActiveMethod(){
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Invoice__c invoi = new Invoice__c();
        invoi.Name = 'test';
        invoi.Customer__c = acc.id;
        insert invoi;
        
        Invoice_Line_Items__c item = new Invoice_Line_Items__c();
        item.Invoice__c = invoi.Id;
        insert item;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoi);
        InvoiceArabic testAccPlan = new InvoiceArabic(sc);
        testAccPlan.getItems();
        
        PageReference pageRef = Page.InvoiceArabic;
        pageRef.getParameters().put('id', String.valueOf(invoi.Id));
        Test.setCurrentPage(pageRef);
        
    }
}