wier/force-app/main/default/objects/Check_List__c/Check_List__c.object-meta.xml
<CustomObject>
    <label>Tendering Checklist</label>
    <nameField>
        <label>Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tendering  Checklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Check_List__c/fields/Assigned_Status__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Status__c</fullName>
    <label>Assigned Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/Check_List__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>Check_List</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Quotation review due date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Quotation_submittal_date__c.field-meta.xml
<CustomField>
    <fullName>Quotation_submittal_date__c</fullName>
    <label>Quotation submittal due date</label>
    <type>Date</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/Win_Probability__c.field-meta.xml
<CustomField>
    <fullName>Win_Probability__c</fullName>
    <label>Win probability (%)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/classes/wr_CheckList_TestClass.cls
@isTest
private class wr_CheckList_TestClass
{
    static testMethod void wr_CheckList_TestClassmethod() 
    {
     
     COpportunity__c oppty = new COpportunity__c();
     oppty.Quotation_submittal_date__c = Date.today(); 
     //oppty.Win_Probability__c = 90;
     insert oppty;
     
     
     Check_List__c checkList = new Check_List__c();
     checkList.Due_date__c= Date.Today();
     checkList.Opportunity__c= oppty.id;
     checkList.Assignee_Comments__c = 'TestingData';
     checkList.Assigned_Status__c = 'Outstanding';
     insert checkList;  
     
     ApexPages.StandardController con = new ApexPages.StandardController(checklist);
     wr_CheckList wrCheckList = new wr_CheckList(con);
     wrCheckList.csave();
     wrCheckList.AddRow();
     wrCheckList.cancel();
     
    }

}