wier/force-app/main/default/objects/Check_List__c/Check_List__c.object-meta.xml
<CustomObject>
    <label>Tendering Checklist</label>
    <nameField>
        <label>Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tendering  Checklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/Check_List__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>COpportunity__c</referenceTo>
    <relationshipName>Check_List</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/COpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>Opp-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

wier/force-app/main/default/objects/COpportunity__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIS</fullName>
            </value>
            <value>
                <fullName>Dubai - APS/RE</fullName>
            </value>
            <value>
                <fullName>Dubai - Oilfield</fullName>
            </value>
            <value>
                <fullName>Iraq</fullName>
            </value>
            <value>
                <fullName>NAI</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Saudi</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/objects/COpportunity__c/fields/CSRDecisionOnBid__c.field-meta.xml
<CustomField>
    <fullName>CSRDecisionOnBid__c</fullName>
    <label>CSR&apos;s Decision on Bid</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

wier/force-app/main/default/classes/Test_wr_CheckList.cls
@isTest
private class  Test_wr_CheckList{    
    
    static testMethod void UnitTest() {

        COpportunity__c Opp = new COpportunity__c(Business_Unit__c = 'Oman',CSRDecisionOnBid__c = 'YES');
        insert Opp;
        
        Check_List__c conlist = new Check_List__c(Opportunity__c = Opp.Id);
        insert conlist;        
        
        ApexPages.StandardController std = new ApexPages.StandardController(conlist);
        PageReference pageRef = Page.wr_CheckList;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', conlist.id);
        wr_CheckList  cont = new wr_CheckList(std);
        cont.csave();
        cont.AddRow();
        cont.Cancel();
        

    }
}